version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-hola
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: holadatabase
    ports:
      - "3306:3306"
    restart: always
